---
title: "DigiHaul Data Task"
author: "Nayyab Mir"
date: "2024-05-16"
output: html_document
---

```{r setup, include=FALSE}
## import packages (download the packages via install.packages("name of package") before running
library(tidyr)
library(lubridate)
library(dplyr)
library(ggplot2)
library(stringr)
library(pscl)
library(ggmap)
library(PostcodesioR)
library(tidygeocoder)
library(Hmisc)
library(terra)
library(geosphere)
library(randomForest)
library(caret)
library(pROC)
library(caTools)
library(ROCit)
library(hms)

```

```{r}
## call data in
GPS_data <- read.csv(paste0(getwd(),"/files/GPS_data.csv"))
shipment_bookings <- read.csv(paste0(getwd(),"/files/Shipment_bookings.csv"))
new_bookings <- read.csv(paste0(getwd(),"/files/New_bookings.csv"))
```

```{r}
##Q1

## combine the shipment bookings and gps data files and tidy date fields

combined_datasets <- left_join(shipment_bookings, GPS_data, by = "SHIPMENT_NUMBER")

combined_datasets$date <- str_sub(combined_datasets$RECORD_TIMESTAMP,1,10)

combined_datasets$FIRST_COLLECTION_SCHEDULE_EARLIEST <- ymd_hms(combined_datasets$FIRST_COLLECTION_SCHEDULE_EARLIEST)

combined_datasets$LAST_DELIVERY_SCHEDULE_LATEST <- ymd_hms(combined_datasets$LAST_DELIVERY_SCHEDULE_LATEST)

```

```{r}

##Q1 continued

df <- combined_datasets %>%
  filter(date >= '2023-10-01' & date <= '2023-12-31') %>%
  arrange(date) %>%
  mutate(Flag = ifelse(as.POSIXct(RECORD_TIMESTAMP) < as.POSIXct(LAST_DELIVERY_SCHEDULE_LATEST) %m+%minutes(30), "Not Late", "Late"))

number_of_timely_shipments <- nrow(subset(df, Flag == c("Not Late")))

number_of_late_shipments <- nrow(subset(df, Flag == c("Late")))

percentage_of_timely_shipments <- number_of_timely_shipments/(number_of_late_shipments + number_of_timely_shipments)*100

percentage_of_timely_shipments

## 84% of shipments met the on-time delivery threshold

```

```{r}

##Q2

##added a notification field to the data set to flag whether or not the associated shippers (PROJECT_ID) require a notification regarding potential late deliveries, and the time of notification (30 minutes before the last scheduled delivery time)

potential_delayed <- df %>%
  mutate(notification_needed = ifelse(RECORD_TIMESTAMP > LAST_DELIVERY_SCHEDULE_LATEST,"Yes",
         "No"),time_of_notification = case_when(notification_needed == "Yes" ~ as.POSIXct(LAST_DELIVERY_SCHEDULE_LATEST) %m-%minutes(30),
                                    notification_needed == "No" ~
                                      NA))

```

```{r}

## Exploratory Analysis

## produce a bar plot showing the average delay (in hours) of deliveries
## between 1st October and 31st December 2023

potential_delayed$RECORD_TIMESTAMP <- ymd_hms(potential_delayed$RECORD_TIMESTAMP)
potential_delayed$LAST_DELIVERY_SCHEDULE_LATEST <- ymd_hms(potential_delayed$LAST_DELIVERY_SCHEDULE_LATEST)
potential_delayed$Month_Year <-format(as.Date(potential_delayed$date), "%Y-%m")

exploratory_analysis_average_delay_of_shipments <- potential_delayed %>%
  filter(notification_needed == "Yes") %>%
  mutate(delay = difftime(RECORD_TIMESTAMP,LAST_DELIVERY_SCHEDULE_LATEST, units = 'hours')) %>%
  group_by(Month_Year) %>%
  arrange(Month_Year) %>%
  summarise(`average delay (hours)` = mean(delay))

barplot_delayed_over_time <- ggplot(exploratory_analysis_average_delay_of_shipments,aes(x=Month_Year, y=`average delay (hours)`)) + geom_bar(position = "dodge",stat = "identity") + labs(x = "YearMonth", y = "Hours") + ggtitle("Average delay of deliveries")

barplot_delayed_over_time

ggsave("barplot_delayed_over_time.png")


## produce a bar plot showing the percentage of on-time deliveries and late deliveries
## between 1st October and 31st December 2023

combined_datasets$Month_Year <-format(as.Date(combined_datasets$date), "%Y-%m")

exploratory_analysis_over_time <- combined_datasets %>%
  drop_na() %>%
mutate(Flag = ifelse(as.POSIXct(RECORD_TIMESTAMP) > as.POSIXct(LAST_DELIVERY_SCHEDULE_LATEST) %m+%minutes(30), "Late", "Not Late")) %>%
  arrange(Month_Year) %>%
  group_by(Month_Year, Flag) %>%
  summarise(total = n()) %>%
  mutate(Percent = total/sum(total)) %>%
  ungroup()
  

barplot_late_over_time <- ggplot(exploratory_analysis_over_time,aes(fill = Flag, x=Month_Year, y=Percent)) + geom_bar(position = "dodge",stat = "identity") + scale_y_continuous(labels = scales::percent) + labs(x = "YearMonth", y = "Percentage of deliveries") + ggtitle("Percentage of on-time and late deliveries")

barplot_late_over_time

ggsave("barplot_late_over_time.png")
```

```{r}

## Q3
## tidy data set for modelling

model_data <- combined_datasets %>%
 filter(complete.cases(.)) %>%
  na.omit() %>%
mutate(Flag = ifelse(as.POSIXct(RECORD_TIMESTAMP) > as.POSIXct(LAST_DELIVERY_SCHEDULE_LATEST) %m+%minutes(30), 'Late', 'Not Late'))

model_data$Flag <- as.factor(model_data$Flag)
model_data$VEHICLE_SIZE <- as.factor(model_data$VEHICLE_SIZE)

##split data into training and testing samples

split <- sample.split(model_data, SplitRatio = 0.8) 

train <- subset(model_data, split == 'TRUE') 
test <- subset(model_data, split == 'FALSE') 

##run logistical regression model with vehicle size, first collection latitude, first collection
##longitude, last delivery latitude and last delivery longitude fields from data

log_model_all_variables <- glm(Flag ~ VEHICLE_SIZE + FIRST_COLLECTION_LATITUDE + FIRST_COLLECTION_LONGITUDE + LAST_DELIVERY_LATITUDE + LAST_DELIVERY_LONGITUDE, data = train, family = binomial())

##produce a summary of the model results

summary(log_model_all_variables)

##retrieve the model accuracy results

pR2(log_model_all_variables)

##see importance ranking of predictors in model

importances <- varImp(log_model_all_variables) 
importances %>%
  arrange(desc(Overall))

##select relevant fields in the testing subset for testing the model

testing_data <- test %>%
  select(VEHICLE_SIZE, FIRST_COLLECTION_LATITUDE,FIRST_COLLECTION_LONGITUDE, LAST_DELIVERY_LATITUDE, LAST_DELIVERY_LONGITUDE,Flag)

##apply model on the testing set

tested_log_model <- predict(log_model_all_variables, newdata = testing_data, type = 'response')

##produce ROC curve to assess the performance of the model

ROCit_obj <- rocit(score=tested_log_model,class=testing_data$Flag)
ROC_Curve <- plot(ROCit_obj, main = "ROC curve -- Logistical Regression")

ROC_Curve

ggsave("ROC_Curve.png")

##tidy the new bookings data set, in particular we are removing the vehicle sizes which
##do not appear in the data used to train the model

new_bookings_cleaned <- new_bookings %>%
  filter(VEHICLE_SIZE != '7.5 T')

##use the model to predict the likelihood (probabilities) of delay for the list of shipments
##in the new bookings data set

tested_new_bookings <- predict(log_model_all_variables, newdata = new_bookings_cleaned, type = 'response')

```

